var alertGreeting;
alertGreeting = 'Hello, WORLD!';
alert (alertGreeting);
var consoleAlert;
consoleAlert = 'first console alert';
console.log (consoleAlert);
var strAlert;
strAlert = 'hello';
console.log (typeof strAlert);
var str;
str = 'world';
console.log (strAlert + ' ' + str);
var numAlert;
numAlert = 123321;
console.log (typeof numAlert);
numAlert = -numAlert;
console.log (numAlert);
var y;
y = 123000;
console.log (numAlert - y);
var x, n, z;
x = 10;
n = 45;
z = '15';
console.log (n*2 - x*x);
console.log (z + x);
console.log (+z + x);
console.log (n%x);
x++;
console.log (x);
console.log (x++ + +z);
console.log (++x + +z);
var nullAlert = null;
console.log (typeof nullAlert);
var undef;
console.log (typeof undef);
var booleanAleret;
booleanAleret = true;
console.log (typeof booleanAleret);
var objAlert;
objAlert = {name: 'Darya', age: 26};
console.log (typeof objAlert);
console.log (x > y);
console.log (nullAlert > y);
console.log (nullAlert === nullAlert);
console.log (nullAlert >= nullAlert);
console.log (nullAlert != numAlert);
console.log (0 == false);
console.log (0 != false);
console.log (0 !== false);
console.log (null == undefined);
console.log (undefined == undefined);